[notebook]
dir = "~/Documents/personal-notes"

[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"
id-charset = "hex"
id-length = 6
id-case = "lower"

[group.daily]
paths = ["daily"]

[group.daily.note]
filename = "{{format-date now '%Y/%m/%Y-%m-%d'}}"
template = "daily.md"

[format.markdown]
link-format = "[[{{filename}}|{{title}}]]"
hashtags = false
colon-tags = true

[tool]
fzf-options = "--bind=ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up --border=none --layout=reverse --style=full --tmux=80%"
fzf-preview = "bat --color=always --plain --line-range=:500 {-1}"

[alias]
- = "zk edit --limit 1 --sort modified- $@"
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
random = "zk list --quiet --format full --sort random --limit 1"

[lsp.diagnostics]
dead-link = "warning"
