name: Auto Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1-7,15-21 * 1"

jobs:
  auto_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run update
        run: make update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          title: "ci: auto update"
          body: "Created by the auto-update workflow."
          commit-message: "ci: auto update"
          branch: auto-update
          base: main
          reviewers: "dbreyfogle"
